version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: dev_mysql
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_schema
    ports:
      - 3308:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: dev_pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8183:80

  adminer:
    container_name: dev_adminer
    image: adminer
    restart: always
    ports:
      - 8182:8080
      
/* Only a Basic file to run SQL in Docker with cmd command
docker -compose -f mysql.yml up
After it you can open PHPmyAdmin or Adminer in your browser with localhost:8183 or localhost:8182 and edit the Data Bank freely. */
