# Use postgres/example user/password credentials
version: '3.1'
services:
  postgresql:
    container_name: 'meucontainer'
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: minhasenha
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "seuemail@email.com"
      PGADMIN_DEFAULT_PASSWORD: "senha1"
    ports:
      - "8090:80"
    depends_on:
      - postgresql
      
      # docker-compose.exe -f .\postgres.yml up -d
      # sudo docker exec -it meucontainar pg_dump -p minhasenha -U postgres -d teste >dump.sql
      # or
      # docker exec meucontainer pg_dump -O -Fp --insert -d company -U postgres > dump.sql
